# Generated by Django 5.0.6 on 2025-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Unidad', 'Unidad')], max_length=20),
        ),
    ]
