# Generated by Django 5.0.6 on 2025-12-14 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaensamble',
            name='fecha_elaboracion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
