# Generated by Django 5.0.6 on 2025-12-14 07:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_notaensamble_fecha_elaboracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEnsambleInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ensambles_insumo', to='inventario.insumo')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='inventario.notaensamble')),
            ],
            options={
                'unique_together': {('nota', 'insumo')},
            },
        ),
    ]
