# Generated by Django 5.0.6 on 2025-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_insumo_tercero'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
