# Generated by Django 5.0.6 on 2025-12-15 15:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_notaensambleinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaensambledetalle',
            name='bodega_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_detalle', to='inventario.bodega'),
        ),
        migrations.CreateModel(
            name='TrasladoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='inventario.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='inventario.bodega')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='inventario.notaensambledetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='inventario.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='inventario.talla')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_producto', to='inventario.tercero')),
            ],
        ),
    ]
