# Generated by Django 5.0.6 on 2025-12-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_insumo_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosadicionalesproducto',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
