# Generated by Django 5.0.6 on 2025-11-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_alter_insumo_options_insumo_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno del insumo (opcional)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
