# Generated by Django 5.0.6 on 2025-12-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_notaensambledetalle_bodega_actual_trasladoproducto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notaensambledetalle',
            unique_together={('nota', 'producto', 'talla', 'bodega_actual')},
        ),
    ]
