# Generated by Django 5.0.6 on 2025-12-26 15:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_notaensambledetalle_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.bodega')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.tercero')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='NotaSalidaProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notasalidaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaSalidaAfectacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('detalle_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_afectadas', to='inventario.notaensambledetalle')),
                ('salida_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afectaciones', to='inventario.notasalidaproductodetalle')),
            ],
        ),
    ]
