# Generated by Django 5.0.6 on 2025-11-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_receta_alter_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='inventario.receta')),
            ],
        ),
    ]
