# Generated by Django 5.0.6 on 2025-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_notasalidaproducto_notasalidaproductodetalle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='insumo',
            name='factura',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='insumo',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
