# Generated by Django 5.0.6 on 2025-11-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='receta',
        ),
        migrations.AddField(
            model_name='receta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='inventario.producto'),
        ),
    ]
