# Generated by Django 5.0.6 on 2025-12-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_insumo_descripcion_insumo_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
