# Generated by Django 5.0.6 on 2025-12-27 16:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_insumo_color_insumo_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación'), ('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('CONSUMO_ENSAMBLE', 'Consumo por ensamble'), ('AJUSTE', 'Ajuste')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_resultante', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('factura', models.CharField(blank=True, default='', max_length=120)),
                ('observacion', models.TextField(blank=True, default='')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.insumo')),
                ('nota_ensamble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.notaensamble')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tercero')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['insumo', '-fecha'], name='inventario__insumo__4bb955_idx'), models.Index(fields=['tipo', '-fecha'], name='inventario__tipo_c75384_idx')],
            },
        ),
    ]
