# Generated by Django 5.0.6 on 2025-12-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_bodega_insumo_bodega_receta_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='inventario.bodega'),
        ),
    ]
