# Generated by Django 5.0.6 on 2025-12-27 21:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_insumomovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminadoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INGRESO_EXCEL', 'Ingreso por Excel'), ('AJUSTE', 'Ajuste'), ('SALIDA', 'Salida')], default='INGRESO_EXCEL', max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_global_resultante', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movs_producto_terminado', to='inventario.bodega')),
                ('nota_ensamble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.notaensamble')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movs_terminado', to='inventario.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movs_terminado', to='inventario.talla')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movs_producto_terminado', to='inventario.tercero')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['producto', '-fecha'], name='inventario__product_d7b3d9_idx'), models.Index(fields=['bodega', '-fecha'], name='inventario__bodega__dffd38_idx'), models.Index(fields=['tipo', '-fecha'], name='inventario__tipo_fbb2c3_idx')],
            },
        ),
    ]
