# Generated by Django 6.0.1 on 2026-01-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productoterminadomovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
