# Generated by Django 6.0.1 on 2026-01-10 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0011_insumo_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumomovimiento',
            name='tipo',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('CONSUMO_ENSAMBLE', 'Consumo por ensamble'), ('AJUSTE', 'Ajuste'), ('EDICION', 'Edición')], max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialUniversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('usuario', models.CharField(blank=True, default='Sistema', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='inventario__content_80605c_idx')],
            },
        ),
    ]
