# Generated by Django 6.0.1 on 2026-01-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_insumomovimiento_tipo_historialuniversal'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historialuniversal',
            name='inventario__content_80605c_idx',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='HistorialUniversal',
        ),
    ]
