# Generated by Django 6.0.1 on 2026-01-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_historialuniversal_inventario__content_80605c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talla',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
