# Generated by Django 6.0.1 on 2026-01-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_bodega_es_activo_talla_es_activo_tercero_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
