# Generated by Django 6.0.1 on 2026-01-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_bodega_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
