# Generated by Django 6.0.1 on 2026-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_producto_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuesto',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
