# Generated by Django 6.0.1 on 2026-01-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_impuesto_es_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
