# Generated by Django 6.0.1 on 2026-01-11 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_bodega_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaensambledetalle',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
