# Generated by Django 6.0.1 on 2026-01-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_notaensambledetalle_cantidad_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='insumomovimiento',
            name='nota_ensamble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumomovimientos', to='inventario.notaensamble'),
        ),
        migrations.AlterField(
            model_name='productoterminadomovimiento',
            name='nota_ensamble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_terminados_movimientos', to='inventario.notaensamble'),
        ),
    ]
