# Generated by Django 6.0.1 on 2026-01-20 20:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_operador_alter_insumomovimiento_nota_ensamble_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaensamble',
            name='costo_servicio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='notaensamble',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_ensamble', to='inventario.operador'),
        ),
    ]
